### ISSUE TITLE
Material lists for Tiers

### ISSUE THREAD

**Issue by ToppleTheNun** [deathmarine/DiabloDrops#39]
Material lists for tiers don't work. Using the default tier.yml formatting, but with Materials, the code won't read the Material lists.

``` yaml
Legendary:
  Color: Gold
  Chance: 3
  Material:
  - Diamond_Sword
  - Diamond_Axe
  Enchantments:
    Amt: 7
    Levels: 10
  Lore:
  - 'Required Level: 500'
```

This tier.yml results in all kinds of items, not just diamond swords and diamond axes. The best possible thing to do, I think, is to switch from using material names to using material ids.
